// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAlLJ3-N7COOVlhr_NQRtPuMjnjAk4zwI',
    appId: '1:52553550943:web:2c5461f0cabbc51f1d1fea',
    messagingSenderId: '52553550943',
    projectId: 'findo-isar',
    authDomain: 'findo-isar.firebaseapp.com',
    storageBucket: 'findo-isar.appspot.com',
    measurementId: 'G-0ZLQ7J46QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyqRe4nDeHqB9NQWsg6kDJaa25h1LLlCI',
    appId: '1:52553550943:android:421eb57fa9eb88ee1d1fea',
    messagingSenderId: '52553550943',
    projectId: 'findo-isar',
    storageBucket: 'findo-isar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4TmHDFgtPgsQVrkVaxLj7I8Xtk82VOvQ',
    appId: '1:52553550943:ios:c9b683670654384f1d1fea',
    messagingSenderId: '52553550943',
    projectId: 'findo-isar',
    storageBucket: 'findo-isar.appspot.com',
    iosClientId: '52553550943-8c0srjpfqfiaka46h0k8fufbv2pbprh4.apps.googleusercontent.com',
    iosBundleId: 'com.findoisar.findoIsar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4TmHDFgtPgsQVrkVaxLj7I8Xtk82VOvQ',
    appId: '1:52553550943:ios:c9b683670654384f1d1fea',
    messagingSenderId: '52553550943',
    projectId: 'findo-isar',
    storageBucket: 'findo-isar.appspot.com',
    iosClientId: '52553550943-8c0srjpfqfiaka46h0k8fufbv2pbprh4.apps.googleusercontent.com',
    iosBundleId: 'com.findoisar.findoIsar',
  );
}
